num1 = int(input("enter value1:"))
num2 = int(input("enter value2:"))
sum = (int(num1) + int(num2))
sub = (int(num1) - int(num2))
mul = (int(num1) * int(num2))
div = (int(num1) / int(num2))
print("The sum of {0} and {1} is {2} ".format(num1 , num2 , sum))
print("The sub of {0} and {1} is {2} ".format(num1 , num2 , sub))
print("The mul of {0} and {1} is {2} ".format(num1 , num2 , mul))
print("The div of {0} and {1} is {2} ".format(num1 , num2 , div))